on:
  workflow_dispatch:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Git commit message check and then
    outputs:
      output1: ${{ steps.main.outputs.RESULT }}
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Check Commit Message
        id: "main"
        uses: ./

  after-reaction:
    if: ${{ contains(steps.main.outputs.RESULT, 'REQUIRED_REACTION') }}
    runs-on: ubuntu-latest
    name: After Reaction
    steps:
      - id: "1"
        run: echo "1"

      - id: "2"
        run: echo "2"
