on:
  workflow_dispatch:

jobs:
  git-commit-message-check-and-then:
    runs-on: ubuntu-latest
    name: Git commit message check and then
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Run My Actions
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
